<?php

namespace App\Providers;

use App\Services\Cache\Factory;
use App\Services\CacheManager;
use Illuminate\Support\ServiceProvider;

class CacheServiceProvider extends ServiceProvider
{
    //protected $defer = true;

    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        //
        $this->app->singleton("cache:app", function ($app) {
            return new CacheManager($app);
        });

    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }

//    public function provides()
//    {
//        return [
//            'cache:app',
//        ]; // TODO: Change the autogenerated stub
//    }
}
